import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Container } from "@mui/material";
import Hero from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Eth Nairobi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          height: "100vh",
          width: "100vw",
          background: `
            radial-gradient(circle at 20% 30%, #1A0F28, transparent 60%),
            radial-gradient(circle at 70% 40%, #261437, transparent 60%),
            radial-gradient(circle at 50% 70%, #331945, transparent 60%),
            radial-gradient(circle at 80% 80%, #3F1E54, transparent 60%),
            #0A0612`,
        }}
      >
        <Container maxWidth="xl">
          <Hero />
        </Container>
      </Box>
    </>
  );
}
